version: '3.8'

services:
  server:
    build:
      dockerfile: server.Dockerfile
      context: .
    restart: always

  client:
    build:
      dockerfile: client.Dockerfile
      context: .
    depends_on:
      - server
